### ISSUE TITLE
Bug - Unable To Import

### ISSUE THREAD

**Issue by TurKurT656** [ongakuer/CircleIndicator#10]
Hi,
I've tried to import both of ur libs as dependencies. but non of them imported.
I have this libs as my custom libs:

compile 'com.android.support:appcompat-v7:21.0.3'
compile 'com.nineoldandroids:library:2.4.0'
compile 'com.daimajia.androidanimations:library:1.1.3@aar'
compile 'com.joooonho:selectableroundedimageview:1.0.1'

**Comment by ongakuer** [comment]
Any logs?

**Comment by TurKurT656** [comment]
Just This:

Error:(27, 13) Failed to resolve: me.relex:circleindicator:1.0.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by ongakuer** [comment]
What's your Android Studio version?

**Comment by TurKurT656** [comment]
v1.1.0

**Comment by ongakuer** [comment]
I have created a sample demo.  Can you try this out?
[Download](https://www.dropbox.com/s/iblvfmy3u57cfxj/TestDemo.zip?dl=0)

**Comment by TurKurT656** [comment]
same bug

**Comment by ongakuer** [comment]
Well , I think maybe it's your IDE problem. 
You can copy the source code to your project

**Comment by TurKurT656** [comment]
See this: http://stackoverflow.com/questions/28927986/android-studio-cant-resolve-dependencies
can u change ur gradle version to 1.1.0 and then upload ur lib?

dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

**Comment by ongakuer** [comment]
I don't think so.  
The demo yesterday you tried out, It gradle version was already 1.1.0.  I could totally launch it.

**Comment by TurKurT656** [comment]
I've find the problem. when i updated android studio, the IDE automatically checked offline mode. and that was the reason why i couldnt import new version libs :)
