### ISSUE TITLE
ViewPager is not working for (androidx.viewpager.widget.ViewPager)

### ISSUE THREAD

**Issue by Khosbayar** [ongakuer/CircleIndicator#103]
Android refactored import android.support.v4.view.ViewPager to androidx.viewpager.widget.ViewPager
So we can't use it anymore.
Will you fix your CircleIndicator.java?
If so, please change it ASAP. 

Best regards,
Josh

**Comment by ongakuer** [comment]
Sorry, androidx is still in beta version.  
You can fork this project and change it.

**Comment by hmedat** [comment]
Now it is live
