### ISSUE TITLE
Limited indicator for multiple screen

### ISSUE THREAD

**Issue by brijhub** [ongakuer/CircleIndicator#105]
This library is awesome I have used in one of my project so it works absolutely fine.
Now I have different scenario:

I have total 50 screens in view pager so I don't want to have 50 circular indicator at bottom.
Instead few indicator like 6 or 7 only and these indicator will scroll and move as I swipe in viewpager just like instagram.

Looking for your help.

**Comment by ozankonur** [comment]
@brijhub did you find a solution ?

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/issues/42
