### ISSUE TITLE
No indicator for one page only

### ISSUE THREAD

**Issue by erickva** [ongakuer/CircleIndicator#107]
Hello,
Is there a property/way to disable/hide the indicator if there is only one page?
Thank you.

**Comment by Eyadoos** [comment]
@erickva You've been turning coffee into code for the past 2 decades but you haven't heard of if/else yet?

**Comment by mveroukis** [comment]
I agree with @erickva, some way for the indicator itself to handle the case of a single page would be a nice touch to this. Obviously it's not hard to do that in my code, but it's pretty much gonna look the same in everyone's code, why not refactor that logic into the indicator itself?
