### ISSUE TITLE
Can't set properties programatically

### ISSUE THREAD

**Issue by MikeSimpson** [ongakuer/CircleIndicator#114]
There doesn't appear to be a way to set indicator properties (e.g. ci_drawable) programatically

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/java/me/relex/circleindicator/sample/fragment/CustomAnimationFragment.java#L42

**Comment by ongakuer** [comment]
Well……It's not supported yet.

**Comment by ongakuer** [comment]
And ```Config``` parameters only provide View initialization.  We couldn't update after initialization
