### ISSUE TITLE
How can we set different widths for active and inactive dots

### ISSUE THREAD

**Issue by harshitaahuja** [ongakuer/CircleIndicator#115]
ci_width is setting same width for all tabs. but in my case active tab has more width than inactive tabs as they have different drawables.

**Comment by artemidius** [comment]
In your project's ```res/anim/``` folder create ```circleindicator_anim.xml``` file with following contents

```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    android:duration="@android:integer/config_shortAnimTime">
    <objectAnimator />
</set>
```

Then add ```app:ci_animator``` and ```app:ci_animator_reverse``` attributes to the tag like this

```xml
    <me.relex.circleindicator.CircleIndicator
        ...
        app:ci_animator="@anim/circleindicator_anim"
        app:ci_animator_reverse="@anim/circleindicator_anim"
       ...
     />
```

Library uses default animations, which makes empty items smaller. You define your own empty animation which solves a problem
