### ISSUE TITLE
Dots with SVG images are blurry

### ISSUE THREAD

**Issue by FireZenk** [ongakuer/CircleIndicator#117]
So I'm using two single SVG images (two well defined dots with no blur at all) imported as Android XML resource as enabled/disabled indicator, and here is the result:

![blurry_circle_indicator](https://user-images.githubusercontent.com/1595403/48482074-f2c5c180-e80f-11e8-957a-c16046656e6f.png)

I also noticed that this drawables are used as background of a View instead of a src of a ImageView, so it can be the problem here.

**Comment by ongakuer** [comment]
VectorDrawable has defined width and height.  Scale VectorDrawable would be blurry.
