### ISSUE TITLE
Any idea why my selected indicator is wider than the other circles?

### ISSUE THREAD

**Issue by casolorz** [ongakuer/CircleIndicator#118]
This is my layout:

 ```
<me.relex.circleindicator.CircleIndicator
            android:id="@+id/banner_indicator"
            android:layout_width="wrap_content"
            android:layout_height="6dp"
            app:ci_width="6dp"
            app:ci_height="6dp"
            app:ci_orientation="horizontal"
            android:layout_marginTop="4dp"
            app:layout_constraintLeft_toLeftOf="@+id/banner_pager"
            app:layout_constraintRight_toRightOf="@+id/banner_pager"
            app:layout_constraintTop_toBottomOf="@+id/banner_pager"/>
```

And this is what it ends up looking like:

![image](https://user-images.githubusercontent.com/1638377/49256704-8644e800-f3f5-11e8-8e39-270bab9a173f.png)

**Comment by RomanZhilich** [comment]
The trouble is with default animator included in library `scale_with_alpha.xml`. Create another one manually and reference it from layout with `app:ci_animator=`

**Comment by casolorz** [comment]
Thanks, that fixed it. Is there a recommended way to do the animator? I just changed the 1.8 to 1.0.

**Comment by NecoJack** [comment]
Does not work
“Create another one manually and reference it from layout with app:ci_animator=”

**Comment by casolorz** [comment]
It worked for me but I changed the animator from 1.8 to 1.0.

**Comment by ongakuer** [comment]
@casolorz     

```android:layout_height``` has to be bigger than ```app:ci_height ```

**Comment by ongakuer** [comment]
#129

**Comment by omkar-tenkale** [comment]
Fix for this issue: https://github.com/ongakuer/CircleIndicator/issues/129#issuecomment-1204974400
