### ISSUE TITLE
How to use this inside Recycler view

### ISSUE THREAD

**Issue by Rudra-n-khatri** [ongakuer/CircleIndicator#119]
i want to achieve this kind of effect , is there any way i can use this to achieve similar effect.
https://raw.githubusercontent.com/ogaclejapan/SmartTabLayout/master/art/demo4.gif

**Comment by ongakuer** [comment]
check this project: https://github.com/ongakuer/RecyclerPager

https://github.com/ongakuer/RecyclerPager/tree/master/SmartTabLayout2
