### ISSUE TITLE
What to do if the number of pages is more than the size of the view

### ISSUE THREAD

**Issue by ivan200** [ongakuer/CircleIndicator#120]
For example like in this ScreenShot:
https://yadi.sk/i/IkeDicSziI4Ybw

Am i need always put circleindicator to HorisontalScrollView, and manually scroll it to one of the pages?
Or how can i manage issue if my pager has more than ~25 pages? (or more if phone is landscaped)
If this happens, the user will never see page changes at the beginning and ending.
Or, I also need to have a horisontalProgressBar in parallel with the indicator, disable it, and then show progress instead?
How can I manage if the number of indicators exceeds the size of the view?

Can you please implement feature to fix this issue, or i need to do it somehow by myself?

**Comment by ongakuer** [comment]
#42
