### ISSUE TITLE
Is it planned to support viewpager2?

### ISSUE THREAD

**Issue by togikan** [ongakuer/CircleIndicator#122]
hey there,

Are you planning to make an update to support viewpager2?

**Comment by ongakuer** [comment]
Viewpager2 is based on RecyclerView.  I think it is easy to support

**Comment by dri94** [comment]
Created PR to support this @togikan @ongakuer

**Comment by ongakuer** [comment]
@togikan @dri94 
Release [2.1.1](https://github.com/ongakuer/CircleIndicator/releases/tag/2.1.1)
