### ISSUE TITLE
Dot not changing on page change

### ISSUE THREAD

**Issue by aeroperf** [ongakuer/CircleIndicator#13]
I'm fairly certain I've implemented everything as required, working off the sample with defaultIndicator. But when I change pages, the dots don't change along.

I'm working within a Fragment, in onViewCreated:

`CircleIndicator pagerIndicator = (CircleIndicator) view.findViewById(R.id.pager_indicator);
pagerIndicator.setViewPager(pager);`

I think that's all that is required besides the XML implementation in the view? Or am I missing something?

**Comment by ongakuer** [comment]
What's your XML?

**Comment by aeroperf** [comment]
Straight out of the sample:

`<me.relex.circleindicator.CircleIndicator
            android:id="@+id/indicator_default"
            android:layout_centerInParent="true"
            android:layout_width="fill_parent"
            android:layout_height="40dp"/>`

The dots show, the first one is highlighted, but when I swipe, nothing changes.

**Comment by ongakuer** [comment]
I just release a new version, Would you like to try it ?  And what's your system version?

**Comment by aeroperf** [comment]
I'll give it a shot today, thanks. System version...I'm targeting API 21 and above only, Lollipop.

**Comment by aeroperf** [comment]
I just tried 1.1.3 and still do not get a dot change on page change. 

I have three pages, so three dots. The first dot is highlighted properly and the other two dots are smaller and dimmed. When I change pages, nothing changes with the dots, the first one is still highlighted.

**Comment by ongakuer** [comment]
It's weird……Can you post your java code?  Please make sure do not setOnPageChangeListener again

**Comment by aeroperf** [comment]
Here's what I have (with a few things removed for clarity....pageNames is just a string array):


```@Override
    public void onViewCreated(View view, Bundle savedInstanceState) {

        pager = (ViewPager) view.findViewById(R.id.viewpager);
        final Toolbar toolbar = (Toolbar) getActivity().findViewById(R.id.toolbar);
        toolbar.setTitle(pageNames[0]);
        CircleIndicator pagerIndicator = (CircleIndicator) toolbar.findViewById(R.id.toolbar_pager_indicator);

        // Build the adapter with the known page names and set it to the pager
        adapter = buildMyAdapter(pageNames);
        pager.setAdapter(adapter);
        pagerIndicator.setViewPager(pager);

        // Pager page transformer (animation used when swiping between pages)
        pager.setPageTransformer(true, new DepthPageTransformer());
        pager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }

            @Override
            public void onPageSelected(int position) {
                toolbar.setTitle((pageNames[position]));
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });
    }

**Comment by ongakuer** [comment]
Yes，CircleIndicator has already use OnPageChangeListener. 
You should set OnPageChangeListener to CircleIndicator.
```
pagerIndicator.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }

            @Override
            public void onPageSelected(int position) {
                toolbar.setTitle((pageNames[position]));
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        })
```

**Comment by aeroperf** [comment]
Success! That small, but critical piece I missed. thanks for setting me straight.

**Comment by aizhe11** [comment]
how to change color? fill

**Comment by ongakuer** [comment]
@aizhe11 
You can create custom indicator drawable (xml shape or bitmap).

Use these properties 
````
app:ci_drawable
app:ci_drawable_unselected
````

**Comment by AdeSupriyadi** [comment]
<me.relex.circleindicator.CircleIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:ci_drawable="@drawable/pager_indicator_accent_radius"
            app:ci_drawable_unselected="@drawable/pager_indicator_black_radius"
            android:layout_alignParentBottom="true"/>

the indicator still default, not accent on selected and not black on unselected

**Comment by AdeSupriyadi** [comment]
app:ci_drawable="@drawable/pager_indicator_accent_radius"
app:ci_drawable_unselected="@drawable/pager_indicator_black_radius"

**Comment by AdeSupriyadi** [comment]
`<me.relex.circleindicator.CircleIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:ci_drawable="@drawable/pager_indicator_accent_radius"
            app:ci_drawable_unselected="@drawable/pager_indicator_black_radius"
            android:layout_alignParentBottom="true"/>`
