### ISSUE TITLE
set size for inactive dots

### ISSUE THREAD

**Issue by mt131** [ongakuer/CircleIndicator#132]
why my selected indicator is wider than the other circles?
can i set them equal size?

**Comment by buitrungkhang** [comment]
Author using scale with alpha for default, it like below 
`<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    android:duration="@android:integer/config_shortAnimTime">

    <objectAnimator
        android:propertyName="alpha"
        android:valueType="floatType"
        android:valueFrom="0.5"
        android:valueTo="1.0"/>

    <objectAnimator
        android:propertyName="scaleX"
        android:valueType="floatType"
        android:valueFrom="1.0"
        android:valueTo="1.8"/>

    <objectAnimator
        android:propertyName="scaleY"
        android:valueType="floatType"
        android:valueFrom="1.0"
        android:valueTo="1.8"/>
</set>`
If you want to change this default behavior, you should create new anim xml file and override default by ci_animator attribute. In your case, create anim new one with above code and replace 1.8 to 1.
