### ISSUE TITLE
Can Click dot ?

### ISSUE THREAD

**Issue by q460468765** [ongakuer/CircleIndicator#133]

**Comment by Snailedlt** [comment]
I'm wondering the same, if it's not currently possible, that would be a nice addition to the program

**Comment by ongakuer** [comment]
```setIndicatorCreatedListener```
https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/src/main/java/me/relex/circleindicator/BaseCircleIndicator.java#L165

You can set clickListener  by ```onIndicatorCreated(View view, int position)```
