### ISSUE TITLE
in recyclerview it is showing square  not circle

### ISSUE THREAD

**Issue by abbasalid** [ongakuer/CircleIndicator#149]
<me.relex.circleindicator.CircleIndicator2
                        android:id="@+id/indicator"
                        android:layout_width="wrap_content"
                        android:layout_gravity="end"
                        android:gravity="end"
                        app:ci_drawable_unselected="@color/bluenotselected"
                        app:ci_drawable="@color/blueselected"
                        android:layout_height="@dimen/_35sdp"/>

**Comment by ongakuer** [comment]
Use Drawable ```app:ci_drawable```
