### ISSUE TITLE
How to set circleIndicator position?

### ISSUE THREAD

**Issue by zoumy** [ongakuer/CircleIndicator#15]
I tried to add circleIndicator to AutoScrollViewPager,But it doesn't work.
        ImagePagerAdapter imagePagerAdapter = new ImagePagerAdapter(getActivity(),arrayList).setInfiniteLoop(true);
        viewPager.setAdapter(imagePagerAdapter);
        defaultIndicator.setViewPager(viewPager);

**Comment by ongakuer** [comment]
Did you set OnPageChangeListener to AutoScrollViewPager ?(https://github.com/ongakuer/CircleIndicator/issues/13)

**Comment by zoumy** [comment]
@ongakuer It works now,but app:app:ci_drawable_unselected property could not be found #6

**Comment by ongakuer** [comment]
@zoumy https://github.com/ongakuer/CircleIndicator/pull/6#issuecomment-97640167
