### ISSUE TITLE
Move away from jcenter since it'll be shutdown on May 1st 2021

### ISSUE THREAD

**Issue by tfcporciuncula** [ongakuer/CircleIndicator#151]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

This is unfortunate, but there's not much we can do other than moving away from it.

**Comment by leandrofavarin** [comment]
And here's a couple of links that might be helpful for migration:

- https://chris.banes.dev/publishing-to-maven-central/
- https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/PUBLISHING.asciidoc

**Comment by chrisharris77** [comment]
Note that February 28th 2021 is the last date that new artifacts can be published to JCenter, so if there are any new releases planned this could need to be done sooner than May 1st 2021.

**Comment by ongakuer** [comment]
Completed! 
Thanks for reminding

**Comment by DaphnevdVeeke** [comment]
What version did you migrate to Maven? Because I for be JCenter is still being used and I can only find older versions here: https://mvnrepository.com/artifact/me.relex/circleindicator

**Comment by ongakuer** [comment]
wait for 1 or 2 hours

**Comment by DaphnevdVeeke** [comment]
Thanks for the fast response! I'll try again in a few hours :)

**Comment by ongakuer** [comment]
@DaphnevdVeeke  
It can be used.  Do not forget to add ``mavenCentral()``
https://repo1.maven.org/maven2/me/relex/circleindicator/2.1.6/

**Comment by Daphne-CoffeeIT** [comment]
Thanks for the update! It seems like waiting a bit worked, because now it's actually using Maven 🙌
