### ISSUE TITLE
Backward Comapatibility

### ISSUE THREAD

**Issue by patelakshay13890** [ongakuer/CircleIndicator#16]
How can I use this lib & achieve backward compatibility up-to minSdk = 10 ?

**Comment by ongakuer** [comment]
You can use the version 1.0.0. Or You can import library module, and replace some later Animation API with NineOldAndroids.

**Comment by patelakshay13890** [comment]
Sorry I don't know which part of lib. code ti replace for Animation, so can
you help me out for this problem ?

**Comment by ongakuer** [comment]
the new version need minSdk 11.
