### ISSUE TITLE
Zero width and height when creating CircleIndicator programmatically.

### ISSUE THREAD

**Issue by tn0502** [ongakuer/CircleIndicator#17]
Creating a `CircleIndicator` without an `AttributeSet` does not properly set the width, height, and margin of the indicators:

            CircleIndicator indicator = new CircleIndicator(getActivity());

Because `handleTypedArray()` only sets default values when `mIndicatorWidth`/`mIndicatorHeight`/`mIndicatorMargin < 0` but they're not set in any constructor.

**Comment by tn0502** [comment]
I guess the same goes for all the other properties but I never got so far as to see the indicators on-screen.

**Comment by ongakuer** [comment]
Sorry, I forgot this case… 
I will fix it soon.
