### ISSUE TITLE
Licensing Info

### ISSUE THREAD

**Issue by sndurkin** [ongakuer/CircleIndicator#2]
Hi,

Thanks for your project, it has been very helpful in getting a ViewPager working with an indicator. I'd like to use some of your code in my app, what license is this open-sourced under?

Thanks,
Sean

**Comment by ongakuer** [comment]
@sndurkin 
The Apache Software License, Version 2.0
https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/upload.gradle
(line 36)
