### ISSUE TITLE
Dynamic add/remove indicator

### ISSUE THREAD

**Issue by aeroperf** [ongakuer/CircleIndicator#20]
I have a dynamic viewpager, allowing add/remove of pages.Are there plans to adapt CircleIndicator library to handle dynamic add/remove of pages?

**Comment by aeroperf** [comment]
Nevermind. I just have to call setViewpager() on the indicator again after adapter.notifyDataSetChanged()...

**Comment by HappyDr0id** [comment]
I think that it should not be mandatory to reset the viewpager after each notifyDataSetChanged() method call. A listener on the adapter data size change could be implemented to do the necessary work.
