### ISSUE TITLE
The first circle is always active

### ISSUE THREAD

**Issue by drac94** [ongakuer/CircleIndicator#21]
Hi, first of all, great work.
Is there any way to "deactivate" the first circle?, when I set the setCurrentItem in the adapter, the circle on that position is well activated but also the first one.

Regards.

**Comment by eeVoskos** [comment]
I had the same problem when updated from `v1.13` to `v1.14`. With a bit of search in the source code, I saw that `CircleIndicator` now implements `OnPageChangeListener`.

This solution worked for me:
```
mPager.setAdapter(adapter);
mIndicator.setViewPager(mPager);
mPager.addOnPageChangeListener(mIndicator);
```

I think the above behaviour should be reflected in the sample app.

**Comment by drac94** [comment]
Thanks @eeVoskos, sadly that's not working for me, my code look like this

```java
mPager = (ViewPager) findViewById(R.id.pager);
CircleIndicator defaultIndicator = (CircleIndicator) findViewById(R.id.indicator_default);
mPagerAdapter = new ScreenSlidePagerAdapter(getSupportFragmentManager());
mPager.setAdapter(mPagerAdapter);
mPager.setCurrentItem(position);
defaultIndicator.setViewPager(mPager);
mPager.addOnPageChangeListener(defaultIndicator);
```

But doesn't matter which position the ViewPager starts, the first indicator is always active, I'm doing something wrong?

**Comment by drac94** [comment]
nvm, just switching this two lines and now it's working like a charm
```java
mPager.setCurrentItem(position);
defaultIndicator.setViewPager(mPager);
```

**Comment by eeVoskos** [comment]
Try calling `mPager.setCurrentItem(position)` last, after initializing the ViewPager and the CircleIndicator:
```
mPager = (ViewPager) findViewById(R.id.pager);
CircleIndicator defaultIndicator = (CircleIndicator) findViewById(R.id.indicator_default);
mPagerAdapter = new ScreenSlidePagerAdapter(getSupportFragmentManager());
mPager.setAdapter(mPagerAdapter);
defaultIndicator.setViewPager(mPager);
mPager.addOnPageChangeListener(defaultIndicator);
mPager.setCurrentItem(position);
```

**Comment by ongakuer** [comment]
@eeVoskos is right.
