### ISSUE TITLE
Can we use the CircleIndicator with a ViewFlipper ? (no fragment at all)

### ISSUE THREAD

**Issue by afaucogney** [ongakuer/CircleIndicator#23]
My context is to use the indicator in a Dialog, that does not give access to fragment manager.

**Comment by ongakuer** [comment]
[ViewPager](http://developer.android.com/reference/android/support/v4/view/ViewPager.html) as it is called, can show views. You can use [PagerAdapter](http://developer.android.com/reference/android/support/v4/view/PagerAdapter.html) to generate views without fragment manager.
This library work with  ViewPager's ```OnPageChangeListener ```
