### ISSUE TITLE
Can we use the CircleIndicator with a RecyclerView ?

### ISSUE THREAD

**Issue by afaucogney** [ongakuer/CircleIndicator#24]
As recyclerView is the new standard, that may be interesting.

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/issues/23#issuecomment-119771184

**Comment by afaucogney** [comment]
Ok, thanks for commenting, but in this case, RecyclerView doesn't extends ViewPager class. So I'm trying to use it with https://github.com/lsjwzh/RecyclerViewPager.

I'm still working on, but I needed to change (I found no way to extends) the CircleIndicator lib to accept the RecyclerViewPager (that doest'nt extends ViewPager). Is there another way ?

**Comment by ongakuer** [comment]
Sorry ,It's only support for ViewPager.

But you can import CircleIndicator as module, and change ```ViewPager.OnPageChangeListener``` to  ```RecyclerViewPager.OnPageChangedListener``` for yourself.
