### ISSUE TITLE
NoSuchMethodError: android.support.v4.view.ViewPager.removeOnPageChangeListener

### ISSUE THREAD

**Issue by CristianKrieger** [ongakuer/CircleIndicator#25]
It seems the code is trying to access non-existing methods on ViewPager

java.lang.NoSuchMethodError: android.support.v4.view.ViewPager.removeOnPageChangeListener
            at me.relex.circleindicator.CircleIndicator.setViewPager(CircleIndicator.java:127)

**Comment by ongakuer** [comment]
You need upgrade v4 support library in your project. 
[addOnPageChangeListener](http://developer.android.com/reference/android/support/v4/view/ViewPager.html#addOnPageChangeListener(android.support.v4.view.ViewPager.OnPageChangeListener)) and    [removeOnPageChangeListener](http://developer.android.com/reference/android/support/v4/view/ViewPager.html#removeOnPageChangeListener(android.support.v4.view.ViewPager.OnPageChangeListener)) are new methods in ViewPager

**Comment by CristianKrieger** [comment]
You are right. A comment in that line of code would be useful; or adding that info to the documentation.
