### ISSUE TITLE
Selected dot with dynamic add/remove page

### ISSUE THREAD

**Issue by HappyDr0id** [ongakuer/CircleIndicator#27]
First of all, thank you for sharing your work, this material circle indicator is really quite cool ;)

I would like to let you an issue about the selected state of the CircleIndicator with the use of a dynamic viewpager. 

Despite the fact that I have to call the setViewPager() method each time I notify my adapter that the data size has changed to avoid an exception, I also have another problem which can also be bypassed by another method call.

Here is the concerned use of CircleIndicator :
```javascript
mPagerAdapter.add(object); // dynamic add of an object
mPagerAdapter.notifyDataSetChanged(); // notify the data change
mPagerIndicator.setViewPager(mImagesPager); // reset the viewpager to the indicator
mViewPager.setCurrentItem(0, false); // set the current item to the first position
mViewPager.setCurrentItem(mPagerAdapter.getCount()-1, false); // set the current item to the wanted position (the last added object)
```

The question is : why do I set the item to the position 0 just before setting it to wanted position ?
Because it permits me to avoid the following bug : the wanted position in a selected state AND also the first one.
If I directly set the wanted position, I don't know why (for the moment, I will take time to read the CircleIndicator class) but the first indicator will always be selected.

Thanks in advance for your answer !

**Comment by ongakuer** [comment]
Sorry，This lib is not design for dynamic viewpager at first.

I think maybe It will work like this:
```java
mPagerAdapter.add(object);
mPagerAdapter.notifyDataSetChanged(); 
mViewPager.setCurrentItem(mPagerAdapter.getCount()-1, false);  // set the current item to the wanted position
mPagerIndicator.setViewPager(mViewPager); // re-create Indicators .
```
At setViewPager method, we can get [mCurrentPosition](https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/src/main/java/me/relex/circleindicator/CircleIndicator.java#L125) , and selected current position.

**Comment by HappyDr0id** [comment]
I tried your proposition, but if I don't set the ViewPager before changing the current item, it will crash. This is certainly because the indicator don't have the new positions yet.

```javascript
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundResource(int)' on a null object reference
at me.relex.circleindicator.CircleIndicator.onPageSelected(CircleIndicator.java:162)
at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1792)
```

I will try to make a "dynamic viewpager"-ready version of CircleIndicator :)

Thanks for your answer !

**Comment by APBrown** [comment]
@HappyDr0id Does this PR fix your issue? https://github.com/ongakuer/CircleIndicator/pull/28

**Comment by HappyDr0id** [comment]
Well, this pull request seems to be okay for me :)

**Comment by drac94** [comment]
I had the same problem, this was the solution https://github.com/ongakuer/CircleIndicator/issues/21
