### ISSUE TITLE
NoSuchMethodError removeOnPageChangeListener at CircleIndicator.java

### ISSUE THREAD

**Issue by h3clikejava** [ongakuer/CircleIndicator#29]
java.lang.NoSuchMethodError: android.support.v4.view.ViewPager.removeOnPageChangeListener
at me.relex.circleindicator.CircleIndicator.setViewPager(CircleIndicator.java:127)

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/issues/25
