### ISSUE TITLE
Current indicator background color

### ISSUE THREAD

**Issue by AshkanImmortal** [ongakuer/CircleIndicator#3]
Hello there, can you help me change the color of current indicator?

**Comment by ongakuer** [comment]
You can create a new drawable like [this] (https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/src/main/res/drawable/white_radius.xml ) , and change solid color. 

The XML :
```xml
<me.relex.circleindicator.CircleIndicator    
            android:layout_width="match_parent"
            android:layout_height="40dp"
            app:ci_drawable="@drawable/custom_drawable"/>
```

**Comment by AshkanImmortal** [comment]
Thanks for quick reply, yes I did like this, but for example I want to change the color of current indicator, means they are white and second one is yellow

**Comment by ongakuer** [comment]
@AshkanImmortal 
Oh, It will be a lot of code changes.  I'll give you code later.

**Comment by ongakuer** [comment]
@AshkanImmortal 
I have pushed a new branch (  [transition_color](https://github.com/ongakuer/CircleIndicator/tree/transition_color)  ).  
I think TransitionDrawable is a way to change the color of indicator.

**Comment by AshkanImmortal** [comment]
Thanks that's very nice
