### ISSUE TITLE
大兄弟，你这玩意有bug啊，当直接设置viewPager的setCurrentItem时候，下面第一个点状态错误

### ISSUE THREAD

**Issue by h3clikejava** [ongakuer/CircleIndicator#30]
viewPager.setCurrentItem(2);
circleIndicator.setViewPager(viewPager);
第0个和第2个的点都是选中状态，即使手动调用下面一句也没有用
// circleIndicator.onPageSelected(currentIndex);

**Comment by ongakuer** [comment]
请先对Indicator使用setViewPager

然后再对ViewPager setCurrentItem

**Comment by h3clikejava** [comment]
所以大兄弟你在初始化的时候就不应该写成
第一个加载mIndicatorBackgroundResId。因为之后setViewPager时候总会调用onPageSelected初始化mCurrentPosition的

**Comment by ongakuer** [comment]
你是因为需要动态调整viewpager里的数目，所以才需要对Indicator不停的调用setViewPager吗？ 如果是这样你可以试试 https://github.com/ongakuer/CircleIndicator/pull/28
