### ISSUE TITLE
Images and text as background

### ISSUE THREAD

**Issue by turopEDSoft** [ongakuer/CircleIndicator#32]
I would like to use your code to insert a layout information in my app.

I want to know how to insert a picture with text instead of the background color thanks.

I hope I can answer :D

Thanks in advance for any response

**Comment by ongakuer** [comment]
You can set bitmap drawable instead of color drawable
```
<me.relex.circleindicator.CircleIndicator
            app:ci_width="10dp"
            app:ci_height="10dp"
            app:ci_drawable="@drawable/XXX"
            android:layout_width="match_parent"
            android:layout_height="40dp"/>
```

**Comment by turopEDSoft** [comment]
I inserted the code that you gave me.It is interesting but not what ch emi needed.

I wish I could create a presentation of the application, in practice instead of random colors I would see an ImageView and a TextView.

And every time I change the page must also change the content of imageview and TextView

**Comment by ongakuer** [comment]
Here is ViewPager Tutorial：
http://www.androidbegin.com/tutorial/android-viewpager-gallery-images-and-texts-tutorial/
