### ISSUE TITLE
Correct Indicator position is not saved across config changes

### ISSUE THREAD

**Issue by ZakTaccardi** [ongakuer/CircleIndicator#38]
![shamumra58kzak11042015234939](https://cloud.githubusercontent.com/assets/461114/10960106/c8bec446-834e-11e5-9462-3f6322c783d4.png)

Problem code is here I believe. Looks like `mCurrentSelectedPosition` is ignored when creating the indicators.

    private void createIndicators(ViewPager viewPager) {
        this.removeAllViews();
        if(viewPager.getAdapter() != null) {
            int count = viewPager.getAdapter().getCount();
            if(count > 0) {
                this.addIndicator(this.mIndicatorBackgroundResId, this.mAnimationOut);

                for(int i = 1; i < count; ++i) {
                    this.addIndicator(this.mIndicatorUnselectedBackgroundResId, this.mAnimationIn);
                }

            }
        }
    }

**Comment by gunhansancar** [comment]
@ongakuer Are there any news about this bug?

**Comment by ongakuer** [comment]
@gunhansancar 
Will be fixed soon (maybe today).

**Comment by ongakuer** [comment]
Fix  https://github.com/ongakuer/CircleIndicator/commit/f83dfa4f9d33d8725ea0ae6fa9457f99ca4deafb
