### ISSUE TITLE
Doesn't play nice with ParallaxViewPager

### ISSUE THREAD

**Issue by SyedWasiHaider** [ongakuer/CircleIndicator#4]
Hey man,

This is really good work but when I used it with the ParallaxViewPager (see this: https://github.com/andraskindler/parallaxviewpager ), it got rid of the background image (so basically no parallex effect). I looked at the source and saw that you're messing around with the viewpager (is that why?)

Thanks.

**Comment by ongakuer** [comment]
Indicator need set OnPageChangeListener , but ParallaxViewPager already used.
