### ISSUE TITLE
 Failed to resolve: me.relex:circleindicator:1.1.6

### ISSUE THREAD

**Issue by LiuDeng** [ongakuer/CircleIndicator#40]
Error:(15, 13) Failed to resolve: me.relex:circleindicator:1.1.6
<a href="openFile:D:/QiuDuanRiBao/joke/photodraweeview/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by ongakuer** [comment]
Please add MavenCentral to your project.  
I will fix jcenter problem soon.

```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

**Comment by ongakuer** [comment]
Fixed.
