### ISSUE TITLE
"Infinite mode" or how to show indicators for a lot of pages?

### ISSUE THREAD

**Issue by rihardgDev** [ongakuer/CircleIndicator#42]
Hello, 
first of all, good work with everything. I have a lot of pages in my pageviewer (more than 60 entries) and i'm trying to implement that only 3 or 4 (or any other small number) of indicators is visible and that the selected one is in the middle and when you scroll on either side it just repeats until you reach the end. Currently if i implement the indicator, it tries to show a dot for every page in the page adapter and because i have so many they don't fit on the layout plus  it looks very ugly. Any suggestions how to implement it?

**Comment by ongakuer** [comment]
Sorry, It will not supported.
In this case，I think you can use another lib or use numbers 
e.g. https://github.com/ManuelPeinado/NumericPageIndicator
