### ISSUE TITLE
NullPointerException when setViewPager

### ISSUE THREAD

**Issue by devflow** [ongakuer/CircleIndicator#44]
```java
java.lang.NullPointerException at 
    me.relex.circleindicator.CircleIndicator$1.onPageSelected(CircleIndicator.java:179)
    me.relex.circleindicator.CircleIndicator.setViewPager(CircleIndicator.java:151)
```
At first, setViewPager with 3 items.
User selected page at 3rd, and then call setViewPager again with only 2 items.
``` getChildAt(mLastPosition) ``` will be null.

need to consider handle ``NullPointerException`` when ``currentIndicator`` is null.

Thanks.

**Comment by ongakuer** [comment]
You have set two different ViewPager to the Indicator?

**Comment by devflow** [comment]
@ongakuer No. I just use this lib in ```RecyclerView```. so i have to setAdapter again when every ``onBindViewHolder()`` called.

**Comment by ongakuer** [comment]
I think you can setAdapter on ```onCreateViewHolder```, and update Adapter outside.

**Comment by devflow** [comment]
@ongakuer thanks. that's perfect. why can't i think this way. thanks again. 

i will close this issue.
