### ISSUE TITLE
java.lang.NoClassDefFoundError: me/relex/circleindicator/R$styleable 

### ISSUE THREAD

**Issue by shippud3n** [ongakuer/CircleIndicator#45]
when i calling the class it got erorr like this :
The following classes could not be instantiated:
- me.relex.circleindicator.CircleIndicator (Open Class, Show Exception, Clear Cache)
 the IDE  Exception Details 
java.lang.NoClassDefFoundError: me/relex/circleindicator/R$styleable   at me.relex.circleindicator.CircleIndicator.handleTypedArray(CircleIndicator.java:59)   at me.relex.circleindicator.CircleIndicator.init(CircleIndicator.java:50)   at me.relex.circleindicator.CircleIndicator.<init>(CircleIndicator.java:44)   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394) Copy stack to clipboard

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/issues/31

**Comment by shippud3n** [comment]
oke thanks, i add manualy to my project....
and it worked, thank you...
