### ISSUE TITLE
发现内存泄露

### ISSUE THREAD

**Issue by doubleDragon** [ongakuer/CircleIndicator#50]
在项目中LeakCanary检测了内存泄露
使用场景:CircleIndicator搭配ViewPager作为RecyclerView的一个Item

* Retaining: 4.0 KB.
* Reference Key: 355d4985-ef1f-4d93-a3ff-6d7cd0a8d2e1
* Device: OnePlus ONEPLUS A0001 A0001
* Android Version: 5.0.2 API: 21 LeakCanary: 1.4-beta1 02804f3
* Durations: watch=5074ms, gc=208ms, heap dump=1507ms, analysis=35894ms

In com.qingsongchou.social:1.0.3:1.
* com.qingsongchou.social.ui.activity.project.detail.ProjectDetailSaleActivity has leaked:
* GC ROOT android.view.Choreographer$FrameDisplayEventReceiver.this$0
* references android.view.Choreographer.mCallbackQueues
* references array android.view.Choreographer$CallbackQueue[].[1]
* references android.view.Choreographer$CallbackQueue.mHead
* references android.view.Choreographer$CallbackRecord.action
* references android.animation.ValueAnimator$AnimationHandler.mAnimations
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references android.animation.ObjectAnimator.mInterpolator
* references me.relex.circleindicator.CircleIndicator$ReverseInterpolator.this$0
* references me.relex.circleindicator.CircleIndicator.mContext
* leaks com.qingsongchou.social.ui.activity.project.detail.ProjectDetailSaleActivity instance

**Comment by ongakuer** [comment]
这个跟进貌似一直走到系统的Interpolator里…

**Comment by doubleDragon** [comment]
```java
private Animator createAnimatorIn(Context context) {
        Animator animatorIn;
        if (mAnimatorReverseResId == 0) {
            animatorIn = AnimatorInflater.loadAnimator(context, mAnimatorResId);
            animatorIn.setInterpolator(new ReverseInterpolator());
        } else {
            animatorIn = AnimatorInflater.loadAnimator(context, mAnimatorReverseResId);
        }
        return animatorIn;
    }
```
问题是出在这个ReverseInterpolator上，当界面finish的时候，持有了Context引用，这个我在其他机型上测试没有发现，只在一加的手机上出现了。

**Comment by ongakuer** [comment]
抱歉我没有一加手机来测试。
你可以试试在 View 的 onDetachedFromWindow 时把相关的 Animator 和 Interpolator 回收

**Comment by smallgirl** [comment]
LoopViewPager 滑动几页后手机会卡死。小米4，nexus 5 所有手机都是

**Comment by ongakuer** [comment]
@smallgirl 你是运行Sample里的LoopViewPager会卡死吗？ 刚好有台 Nexus 5，但没有复现。

**Comment by smallgirl** [comment]
LoopViewPager 这个 快速滑动几页，我的nexus是6.01的系统 小米4是5.0的系统，就是滑到边缘的时候 会滑不动，或者出现下个页面的半屏幕 卡着。

**Comment by smallgirl** [comment]
@ongakuer 快速滑动 向右面滑动5-10个循环，然后向左滑动，没出现的话，再向右滑动

**Comment by ongakuer** [comment]
@smallgirl 复现了，你这是滑的速度实在有点夸张…在头尾替换的时候如果快速滑动会卡。这个是 LoopViewPager 的问题。

**Comment by smallgirl** [comment]
不只是速度的问题，滑到一定页数后，在往回慢滑动 也会卡，确实是LoopViewPager 的问题，循环viewpager的实现方式很多，自定view group 或者viewpager的adapter返回Integer.MAX_VALUE

**Comment by ongakuer** [comment]
恩，用LoopViewPager因为使用的人多。而且对外的暴露的数据是正确的。
