### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by ivazhnov** [ongakuer/CircleIndicator#51]
```java
private final OnPageChangeListener mInternalPageChangeListener = new OnPageChangeListener() {
...
...
...
            if (mLastPosition >= 0) {
                View currentIndicator = getChildAt(mLastPosition);
                currentIndicator.setBackgroundResource(mIndicatorUnselectedBackgroundResId);
                mAnimatorIn.setTarget(currentIndicator);
                mAnimatorIn.start();
            }
```

currentIndicator could be null, if there is no last position any more(like remove view from viewpager

**Comment by coyarzun89** [comment]
I receive the same crash!

**Comment by ongakuer** [comment]
Did you use latest version?

I don't know how you remove view from Viewpager. 
PagerAdapter doesn't update by default.  http://stackoverflow.com/questions/7263291/viewpager-pageradapter-not-updating-the-view

**Comment by ivazhnov** [comment]
ver me.relex:circleindicator:1.1.8

I know about the updating issue, so I update PagerAdapter by setting new adapter.
like this:

`
mViewPager.setAdapter(new ProfileAdapter(getSupportFragmentManager(), data.getResult()));
mCircleIndicator.setViewPager(mViewPager);
`

**Comment by coyarzun89** [comment]
I'm using the last version: compile 'me.relex:circleindicator:1.1.8@aar'
I'm also setting a new adapter, but I received the crash when I set again the ViewPager.

<img width="589" alt="screen shot 2016-04-05 at 4 40 55 pm" src="https://cloud.githubusercontent.com/assets/1242575/14295745/4613e31a-fb4d-11e5-8771-75578bcd88d2.png">
`
