### ISSUE TITLE
using with LoopRecyclerViewPager

### ISSUE THREAD

**Issue by jintoga** [ongakuer/CircleIndicator#55]
Hello! I tried to use your CircleIndicator class with this library https://github.com/imbryk/LoopingViewPager. I managed to get the position works correctly. but i'm having a problem that the animation is quite slow or i may say it delays when i swipe fast, it seems ok when i swipe slower as you can see in [my video](https://youtu.be/atQ2ADn-3G8). Much appreciate if you could have a look at my repository: https://github.com/jintoga/TestInfiniteSwipeGallery

**Comment by ongakuer** [comment]
You can configure  ```app:ci_animator``` with your animator.

https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/src/main/res/animator/scale_with_alpha.xml#L3
