### ISSUE TITLE
Make selected and unselected dots the same radius size

### ISSUE THREAD

**Issue by rajohns08** [ongakuer/CircleIndicator#56]
I have implemented a custom drawable for both selected and unselected states.

**selected_dot.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape
    android:shape="oval"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/red"/>
    <size android:width="10dp" android:height="10dp" />
</shape>
```

**unslected_dot.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape
    android:shape="oval"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/white"/>
    <size android:width="10dp" android:height="10dp" />
</shape>
```

As you can see in my drawable files, both dots have the same size of `10dp`, however when running the application, the unselected dots appear smaller than the selected dot.

Here is how I'm using the drawables in the `CircleIndicator`:
```xml
<me.relex.circleindicator.CircleIndicator
    android:id="@+id/circle_indicator"
    android:layout_width="match_parent"
    android:layout_height="48dp"
    app:ci_drawable="@drawable/selected_dot"
    app:ci_drawable_unselected="@drawable/unselected_dot" />
```

**Comment by ongakuer** [comment]
Because the default animator is [scale_with_alpha](https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/src/main/res/animator/scale_with_alpha.xml) .

you can configure ```app:ci_animator``` with your custom animator

**Comment by Ronakgadhia** [comment]
I am also facing same issue.How can i set same radius for selected and deselected circle?
 Can you get rid out of it?

**Comment by crgarridos** [comment]
As @ongakuer said you have to change your `app:ci_animator`

Create a file named `alpha.xml` into `res/animator` repertory;

```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    android:duration="@android:integer/config_shortAnimTime">

    <objectAnimator
        android:propertyName="alpha"
        android:valueType="floatType"
        android:valueFrom="0.5"
        android:valueTo="1.0"/>
</set>
```

and then set your `CircleIndicator` with:

```xml
app:ci_animator="@animator/alpha"
```
