### ISSUE TITLE
This makes ScrollView/RecyclerView laggy

### ISSUE THREAD

**Issue by redmanit** [ongakuer/CircleIndicator#61]
My ScrollView/RecyclerView has a ViewPager and CircleIndicator as header and it's laggy when scroll to top. When I remove CircleIndicator (setVisibility(View.GONE)) it's smooth as butter. Tested on average devices ZenFone 5 and Oppo R7 Lite.

**Comment by cbriseno** [comment]
Same here, tested on HTC One.

**Comment by TheFinestArtist** [comment]
Hey guys, have you try remove the animator? I think the animator using lots of operations.
I set the animator with duration 0 and do nothing. And it makes the pager speed faster.

**Comment by ongakuer** [comment]
@TheFinestArtist Try [this]( https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/res/animator/indicator_no_animator.xml)

**Comment by hackware1993** [comment]
@redmanit https://github.com/hackware1993/MagicIndicator, have a try.
