### ISSUE TITLE
How to choose second type from Example Gif

### ISSUE THREAD

**Issue by mladenrakonjac** [ongakuer/CircleIndicator#66]
I would like to have rectangles instead of circles. How I can do that?

**Comment by ongakuer** [comment]
Use ```app:ci_drawable```
https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/res/layout/fragment_sample_custom_animation.xml#L20

custom drawable: 
https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/res/drawable/black_radius_square.xml
