### ISSUE TITLE
Compile failure in Android Studio 1.1

### ISSUE THREAD

**Issue by wangbourne** [ongakuer/CircleIndicator#7]
as titled

**Comment by ongakuer** [comment]
Any logs?  I have updated Android Studio to 1.1.0 .
It seems all right.

**Comment by wangbourne** [comment]
Error:No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by ongakuer** [comment]
Remove the last line of [build.gradle](https://github.com/ongakuer/CircleIndicator/blob/master/circleindicator/build.gradle#L27) and try again.

**Comment by wangbourne** [comment]
I think the correct answer should be:
add following lines in gradle.properties

sonatypeRepo=
sonatypeUsername=
sonatypePassword=

**Comment by ongakuer** [comment]
There are personal properties for publish module. you would not use it.
