### ISSUE TITLE
Animation circle small and big 

### ISSUE THREAD

**Issue by vadol** [ongakuer/CircleIndicator#70]
I want to animated circle Indicator with not animation small and large .Only small indicator when selected or not viewpager.

**Comment by w3ggy** [comment]
You need to set this animator by "app:ci_animator" property.
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
     android:duration="@android:integer/config_shortAnimTime">

    <objectAnimator
        android:propertyName="alpha"
        android:valueType="floatType"
        android:valueFrom="0.5"
        android:valueTo="1.0"/>
</set>
```

**Comment by li2** [comment]
@ongakuer thanks for this lib, but can you add some notes in Readme about the animation, I am assuming others might have encountered the same question here. thanks
