### ISSUE TITLE
怎么让CircleIndicator的点不变大，只是颜色变了

### ISSUE THREAD

**Issue by renyanxu2000** [ongakuer/CircleIndicator#77]

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/java/me/relex/circleindicator/sample/fragment/ChangeColorFragment.java


https://github.com/ongakuer/CircleIndicator/blob/f7115662daa13351953df7bbb1dfce6473c804c1/sample/src/main/res/layout/fragment_sample_change_color.xml
