### ISSUE TITLE
Circle trimming from top on Tablet 

### ISSUE THREAD

**Issue by Ajmalajji** [ongakuer/CircleIndicator#79]
The circle indicator is working very fine upto 6 inches phones. But on tablet, the "Selected" white circle is slightly trimming from the upper edge making it flat from the top. 
Any solution ?
![screenshot_2017-02-20-14-06-05](https://cloud.githubusercontent.com/assets/5016570/23118530/4dabc784-f776-11e6-92f0-e006e345e58a.png)

**Comment by Ajmalajji** [comment]
Removing the following "rotation" animation from Animator.xml resolved the circle trimming. 
    <objectAnimator
        android:propertyName="rotation"
        android:valueType="floatType"
        android:valueFrom="0"
        android:valueTo="200"/>

**Comment by ongakuer** [comment]
Set ``` layout_height``` value larger
