### ISSUE TITLE
Throws NullPointerException when there already setViewPager, again setViewPager called.

### ISSUE THREAD

**Issue by bhbfhfb** [ongakuer/CircleIndicator#8]
Throws NullPointerException when there already setViewPager, again setViewPager called.

...
PagerAdapter aAdapter = new Page4Adapter();//Page count 4.
PagerAdapter bAdapter = new Page3Adapter();//Page count 3.
ViewPager pager = find...
pager.setAdapter(aAdapter);
...
pager.setCurrentItem(3,false);
...
setViewPager(bAdapter);//<- here
...

I have modified the code.

![2015-03-06 10 41 36](https://cloud.githubusercontent.com/assets/2010785/6518735/748049fc-c3ed-11e4-9a46-1fd4d23bde92.png)

    public void setViewPager(ViewPager viewPager) {
        mViewpager = viewPager;
        mCurrentPosition = mViewpager.getCurrentItem();
        createIndicators(viewPager);
        mViewpager.setOnPageChangeListener(this);
        onPageSelected(mCurrentPosition);
    }

    @Override public void onPageSelected(int position) {
        if (mViewPagerOnPageChangeListener != null) {
            mViewPagerOnPageChangeListener.onPageSelected(position);
        }

        if (mAnimationIn.isRunning()) mAnimationIn.cancel();
        if (mAnimationOut.isRunning()) mAnimationOut.cancel();

        View currentIndicator = getChildAt(mCurrentPosition);
        currentIndicator.setBackgroundResource(mIndicatorUnselectedBackground);
        mAnimationIn.setTarget(currentIndicator);
        mAnimationIn.start();

        View selectedIndicaotr = getChildAt(position);
        selectedIndicaotr.setBackgroundResource(mIndicatorBackground);
        mAnimationOut.setTarget(selectedIndicaotr);
        mAnimationOut.start();

        mCurrentPosition = position;
    }

**Comment by ongakuer** [comment]
Would you like to open a pull request?

**Comment by bhbfhfb** [comment]
posted a pull request
:smile:

**Comment by ongakuer** [comment]
merged
