### ISSUE TITLE
Automatically slide to the next photo

### ISSUE THREAD

**Issue by jaybkim1** [ongakuer/CircleIndicator#81]
Is there a way to make image gallery(Let's say three photos) automatically slide to the next one?

From Photo#1 to Photo#2 after certain seconds, 
From Photo#2 to Photo#3 after certain seconds,

And Photo#3 to Photo #1 after certain seconds,
From Photo#1 to Photo #2 after certain seconds,
,,,,
,,,,
infinite

**Comment by AlexanderIgnacz** [comment]
+1

**Comment by ongakuer** [comment]
Infinite  Sample
https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/java/me/relex/circleindicator/sample/fragment/LoopViewPagerFragment.java

**Comment by AlexanderIgnacz** [comment]
Yes, the loop viewpager is awesome but I wanted you to provide Auto-Play feature.
Never mind. I used timer for sliding automatically at some intervals.

**Comment by ongakuer** [comment]
Create a Handler and invoke `viewPager.setCurrentItem`  with `postDelayed` or  `sendMessageDelayed`

**Comment by AlexanderIgnacz** [comment]
Alright, that's what I did. :)
