### ISSUE TITLE
Increase size of inactive page indicator

### ISSUE THREAD

**Issue by dkdilipkumar** [ongakuer/CircleIndicator#83]
Added corner, padding and stroke for inactive pager indicator shape but still size is unchanged.

**Comment by serjTi** [comment]
this question is important for me to!

**Comment by dkdilipkumar** [comment]
I resolved the problem for me by changing **indicator_animator.xml** file the value of android:valueFrom="0.9" and android:valueTo="1.0"[No Change here]
Ex.
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    android:duration="@android:integer/config_shortAnimTime">
    <objectAnimator
        android:propertyName="alpha"
        android:valueType="floatType"
        android:valueFrom="0.9"
        android:valueTo="1.0"/>
</set>

**Comment by dkdilipkumar** [comment]
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    android:duration="@android:integer/config_shortAnimTime">
    <objectAnimator
        android:propertyName="alpha"
        android:valueType="floatType"
        android:valueFrom="0.9"
        android:valueTo="1.0"/>
</set>

**Comment by serjTi** [comment]
indicator_animator.xml - is it your own file or default in library?
