### ISSUE TITLE
Notify Circle Indicator that Viewpager was changed

### ISSUE THREAD

**Issue by huzain07** [ongakuer/CircleIndicator#86]
Is there any way to notify circle indicator when my view pager is changed? 
Example, when i initialize viewpager and circle indicator, my viewpager just contain 0 image, but at some reason i add it so my viewpager contain 3 image. And the result is no circle indicator cz when initialize my pager didnt have any image.

**Comment by ongakuer** [comment]
[DynamicAdapterFragment](https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/java/me/relex/circleindicator/sample/fragment/DynamicAdapterFragment.java)

**Comment by huzain07** [comment]
sorry, but it's still not showing the indicator

**Comment by ongakuer** [comment]
Did you register DataSetObserver?
https://github.com/ongakuer/CircleIndicator/blob/master/sample/src/main/java/me/relex/circleindicator/sample/fragment/DynamicAdapterFragment.java#L39

**Comment by huzain07** [comment]
When initialize

```
mViewPager = (ViewPager) findViewById(R.id.viewPageAndroid);
        adapterView = new SliderAdapter(this,slideListMain);
        mViewPager.setAdapter(adapterView);

        indicator = (CircleIndicator) findViewById(R.id.indicator);
        indicator.setViewPager(mViewPager);
```

When data changed

```
adapterView.notifyDataSetChanged();
adapterView.registerDataSetObserver(indicator.getDataSetObserver());
```

**Comment by ongakuer** [comment]
Register DataSetObserver when you initialize

**Comment by huzain07** [comment]
ah ok, thanks
