### ISSUE TITLE
Failed to resolve: me.relax:circleindicator:1.2.2

### ISSUE THREAD

**Issue by TheBaileyBrew** [ongakuer/CircleIndicator#90]
Failed to resolve: me.relax:circleindicator:1.2.2 
Show in File 
Show in Project Structure dialog

It looks like the source is no longer accessible here because if I navigate to circle.me, I receive this error.
"Services for this domain have been discontinued"

**Comment by ongakuer** [comment]
me.rel【e】x:circleindicator:1.2.2@aar
