### ISSUE TITLE
How to change selected indicator drawable by programatically?

### ISSUE THREAD

**Issue by liuwei-tapatalk** [ongakuer/CircleIndicator#91]
Hi,

We can change selected indicator drawable by `app:ci_drawable` property in xml. But I want to know how to change it dynamically.

I found a method named `configureIndicator` with 7 params, which is too complex. If we can only change one attribute for the indicator?

**Comment by edinofricaniago** [comment]
I have solution for you, I using reflection to change `app:ci_drawable`. `CircleIndicator.java` have variable `mIndicatorBackgroundResId` as it is `private`.

Sample code 
```
CircleIndicator circleIndicator = (CircleIndicator) findViewById(R.id.circleIndicator);
try{
    Field f = circleIndicator.getClass().getDeclaredField("mIndicatorBackgroundResId");
    f.setAccessible(true);
    int mIndicatorBackgroundResId  = f.getInt(circleIndicator);
    mIndicatorBackgroundResId = R.drawable.red_radius; // change to your drawable here
    circleIndicator.invalidate();
} catch(Exception e){
    e.printStackTrace();
}
```

**Comment by ongakuer** [comment]
@liuwei-tapatalk  @edinofricaniago 
Fork or download sources code. Add some methods if you need.
