### ISSUE TITLE
Circular indicator showing extra dot

### ISSUE THREAD

**Issue by Shrikant-B** [ongakuer/CircleIndicator#94]
Hi, amazing library.
I just have a question, how can I force Circular Indicator showing extra dot irrespective to no of items in viewpager.
For ex. Say viewpager shows '**n**' images so circular indicator would show '**n+1**' dots. And swiping '**nth**' dot will take to desired activity.
Thanks.

**Comment by lzzy12** [comment]
override fun getItemCount(): Int = arrayImage.size+1

**Comment by ongakuer** [comment]
@Shrikant-B   
Trying manual mode in  v1.3.2 / v2.1.4
